### ISSUE TITLE
If the user don't select a choice

### ISSUE THREAD

**Issue by Xationch** [paliari/v-autocomplete#10]
Hi,

I use your plugin to propose to visitors to choose a clothes brand. Everything work well if the visitor choose a brand in the list. But sometimes he does not find what he wants.

The problem is that the v-model don't returning the searchText value.

So, if the autocomplete don't return what the user want, the value he wrote must be saved.

How do you do that?

Thanks for your work.

**Comment by paliari** [comment]
In this case you can use the **change** or **update-items** events

[see the events](https://github.com/paliari/v-autocomplete#events)

**Comment by Xationch** [comment]
I'm using a watcher for detect the change of each input and auto update the db.

Actually, if the user don't select a choice in the list, the value is null. Same if you delete a character. The watcher is never trigger, and nothing is udpated in the db.

My solution was to link the searchText with the v-model. For you it's ok like this ?

```
updateItems (what) {
	this.form.data[this.name] = this.$refs.autocomplete.searchText
	axios.get('/api/' + this.name + '/' + what + '/search')
	.then(({data}) => this.items = data.datas);
}
```

**Comment by Xationch** [comment]
No it's not working like I except. The problem is the value of ```componentItem``` become null when you delete a letter. Why?

**Comment by dflourusso** [comment]
If you select an item and after changes the input, i supposed to the item has changed, then you need to select again to ensure that searchText matches truly the selected item
