### ISSUE TITLE
Source will be overwritten after search

### ISSUE THREAD

**Issue by nicolasxu** [paliari/v-autocomplete#11]
After you enter the search text, the source array got overwritten with search result. Is it a bug? 

update (text) {
      this.items = Animals.filter((item) => {
        return (new RegExp(text.toLowerCase())).test(item.name.toLowerCase())
      })
    }

**Comment by paliari** [comment]
I did not quite understand your doubt.
But I think it would be the **auto-select-one-item** property.
See [Properties](https://github.com/paliari/v-autocomplete#properties)
