### ISSUE TITLE
On pug and stylus

### ISSUE THREAD

**Issue by amadeann** [paliari/v-autocomplete#14]
Hey Guys, 

Thanks for the component. I really like it! Especially the simplicity. 

I have a more theoretical consideration. Is it necessary for you to use pug and stylus? The code for the component is not very long and just to experiment a bit on the forked version you need to set up pug and stylus locally. I know it is your component and you can use whatever you wish, but wouldn't it be easier to stick to plain HTML and CSS? 

For example, I added the 'name' attribute (which is now missing, but can be useful for form submits) to the component in my fork and can't really do a PR, since I 'translated' the pug and stylus code (doesn't make sense to include those dependencies in my project). 

I just would like you to give it a little thought :)

**Comment by paliari** [comment]
Thanks for the tip, we'll follow your suggestion
