### ISSUE TITLE
how about bold/highlight matching text?

### ISSUE THREAD

**Issue by xtrimf** [paliari/v-autocomplete#16]

**Comment by dflourusso** [comment]
Hello @xtrimf 

One propose for this component is to be simple and light.

The [item template](https://github.com/paliari/v-autocomplete#example) is completly customizable, and you can implement your own logic.

**Comment by xtrimf** [comment]
OK. Cool .TNX!

**Comment by krugerdavid** [comment]
sorry for posting here, but wanted to extend this. How can I access the current 'text' inside the item template? Hope not to bother with this question

**Comment by molerat619** [comment]
Thanks for this. How can you use the searchText efficiently in order to highlight the matching text?
