### ISSUE TITLE
min-length property off by one

### ISSUE THREAD

**Issue by ltoshea** [paliari/v-autocomplete#18]
The docs say:
min-len : Min length to trigger the updateItems event

`<v-autocomplete :items="items" :min-len='2' v-model="item" :get-label="getLabel" :component-item='template' @update-items="updateItems">
      </v-autocomplete>`

I would be expecting the update to occur after the second character was entered, currently it seems to do it on n+1 character.

**Comment by paliari** [comment]
thanks for the tip.
It has been fixed in version 1.6.0.

**Comment by ltoshea** [comment]
Great, thanks for the quick response. Really enjoying this component.
