### ISSUE TITLE
Implement select first when user leaves input

### ISSUE THREAD

**Issue by krugerdavid** [paliari/v-autocomplete#19]
hi guys
Is there a way to implement a similiar behavior as the jquery autocomplete? if the user writes some text and a list appears, to 'mark' the first one as possible the current selected? tried to implement @blur and keyup.tab but weren't able to do it.

Similar to this approach
https://stackoverflow.com/questions/22746493/get-the-selected-value-in-jquery-autocomplete-on-blur-function

thanks

**Comment by paliari** [comment]
Blur event was added in version 1.6.0.
With this you can implement your logic.
[see](https://github.com/paliari/v-autocomplete/blob/master/README.md#events)

**Comment by krugerdavid** [comment]
Wow! thanks!!! works smoothly!
