### ISSUE TITLE
1.6.0 Webpack Errors

### ISSUE THREAD

**Issue by ltoshea** [paliari/v-autocomplete#20]
After upgrading from 1.6.0 I get the following from webpack:

[Vue warn]: Unknown custom element: <v-autocomplete> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
found in
---> <TopsPortfolios> at src\components\TopsPortfolios.vue
       <App> at src\App.vue
         <Root>

This is the current initialization that works fine for 1.5.3 but breaks for 1.6.0
`import Vue from 'vue'
import App from './App'
import router from './router'
import BootstrapVue from 'bootstrap-vue'
import Autocomplete from 'v-autocomplete'
import 'v-autocomplete/dist/v-autocomplete.css'
import 'bootstrap/dist/css/bootstrap.css'
import 'bootstrap-vue/dist/bootstrap-vue.css'

Vue.config.productionTip = false
Vue.use(BootstrapVue)
Vue.use(Autocomplete)

/* eslint-disable no-new */
new Vue({
  el: '#app',
  router,
  template: '<App/>',
  components: { App, BootstrapVue, Autocomplete }
})`

Is there anything else I can provide?
End result is no autocomplete box and broken rest of the app.

**Comment by krugerdavid** [comment]
hi @ltoshea 
What I did was to add 
`Vue.component( 'v-autocomplete', Autocomplete );` 
after importing autocomplete.

**Comment by ltoshea** [comment]
Thanks krugerdavid - I'll give this a go. Do you know why this is necessary?

**Comment by paliari** [comment]
Issue fixed, please update to latest version 1.7.0.

**Comment by krugerdavid** [comment]
Thanks @paliari it worked perfectly 👍
