### ISSUE TITLE
Holding Key Down does not trigger multiple key down events

### ISSUE THREAD

**Issue by ltoshea** [paliari/v-autocomplete#21]
If you have a large list and wish to hold the down key to go through the list this does not work. The current active line only seems to update on after the key has been released.

**Comment by ltoshea** [comment]
By keyup, I

**Comment by ltoshea** [comment]
Could this be the solution:
`<div class="v-autocomplete-input-group" :class="{'v-autocomplete-selected': value}">
      <input type="search" v-model="searchText" :placeholder="placeholder" :class="inputClass"
            :disabled="disabled" @blur="blur" @focus="focus" @input="inputChange"
            @keyup.enter="keyEnter" @keyup.up="keyUp" @keyup.down="keyDown">
    </div>`

Change @keyup.down="keydown" to @keydown.down="keyDown"

Will try and do a PR in future, currently can't build on this box.

**Comment by paliari** [comment]
thanks for the tip.
It has been fixed in version 1.7.1.

**Comment by ltoshea** [comment]
If this is the solution, I think @keyup.up should also change.

**Comment by ltoshea** [comment]
Awesome, thanks for your speedy response. Happy to do PR's in future if you include build scripts.

**Comment by krugerdavid** [comment]
I will be happy to PR as well @paliari @ltoshea 👍

**Comment by krugerdavid** [comment]
@paliari I'm not sure if it's related.. but, when moving with the arrows to an item in the list.. and the pressed 'tab' for example.. the item is not selected.. is there a way around for this?

**Comment by dflourusso** [comment]
@krugerdavid Press 'Enter' instead of 'tab'

**Comment by krugerdavid** [comment]
hahaha @dflourusso of course.. but what about the several user who still uses 'tab'?? tried to use the blur prop, but the model isn't selected if the user press tab for example.

**Comment by dflourusso** [comment]
@krugerdavid Implemented.
Update to version 1.7.2
