### ISSUE TITLE
v-autocomplete-item not set to active on hover

### ISSUE THREAD

**Issue by ltoshea** [paliari/v-autocomplete#22]
When hovering over an item in the list the class is not set to active, meaning when styling the element you have to do something like:
`.v-autocomplete .v-autocomplete-list .v-autocomplete-list-item:hover{
    background-color:#a488a5;
    color:white;
    cursor: pointer;
}`

If you are hovering over an element with the mouse and then use the keyboard to navigate the list you end up with a :hover style and a style on the active element like so:
`.v-autocomplete .v-autocomplete-list .v-autocomplete-list-item.v-autocomplete-item-active{
    color:white;
    background-color:#a488a5;
}`
Resulting in it looking like two things are selected. I'd suggest making the class active on the element you are hovering over.

Equally happy to be show another way to do this.
Thanks

**Comment by paliari** [comment]
tanks, update to version 1.7.3

**Comment by ltoshea** [comment]
Great, thanks for updating!
