### ISSUE TITLE
enable autofocus

### ISSUE THREAD

**Issue by Kustopher** [paliari/v-autocomplete#27]
Is it possible to enable autofocus on page load for v-autocomplete? This would be nice!

Like seen on properties of vuetify v-text-field: https://vuetifyjs.com/components/text-fields

**Comment by paliari** [comment]
you can use the **input-attrs** to pass attributes to the input search.
See [Properties](https://github.com/paliari/v-autocomplete#properties)

**Comment by Kustopher** [comment]
perfect!

this is working:
`:input-attrs="{'autofocus':true}"`
