### ISSUE TITLE
:input-attrs="{'class':'form-group'}" not working

### ISSUE THREAD

**Issue by daniel-farina** [paliari/v-autocomplete#28]
HI, 

I tried adding this several times but the input is not picking up the class. 
```
:input-attrs="{'class':'form-group'}"
```
I also tried
```
input-attrs="{'class':'form-group'}"
```
![image](https://user-images.githubusercontent.com/13665117/32646143-24de367c-c5b9-11e7-990f-b64fcef8b6f8.png)

Source code:
![image](https://user-images.githubusercontent.com/13665117/32646087-c9cf872c-c5b8-11e7-8d35-92643ed895e1.png)

Dev tools output: 

![image](https://user-images.githubusercontent.com/13665117/32646123-fd3c708e-c5b8-11e7-8c1a-b50f8c9d43cb.png)

Any advice? 

Thank you

**Comment by karimhossenbux** [comment]
You can try :

`:input-class="'form-group'"`

**Comment by paliari** [comment]
```
:input-attrs="{'class': 'form-group'}"
```

This should work, check the Vuejs version and v-autocomplete.
