### ISSUE TITLE
keep-open property is ignored on empty items list

### ISSUE THREAD

**Issue by penyaev** [paliari/v-autocomplete#30]
Hi,

The `keep-open` property is in fact not working in case when `items` is an empty array: the list element is removed from the DOM, but it should not.

This breaks my UX since this list is always open and has fixed height. In case when user enters text which results in empty result list, list is removed from DOM and there occurs an unpleasant snapping in interface.

**Comment by paliari** [comment]
[See #31 ](https://github.com/paliari/v-autocomplete/pull/31)
