### ISSUE TITLE
Can't set empty value

### ISSUE THREAD

**Issue by saxap** [paliari/v-autocomplete#34]
Hello.
In my project i need to unset selected values and clear inputs, but something goes wrong, model in component behaves like non reactive variable.

If i try to set empty value to model, input ignore it, but work if i set non empty value.

In fiddle select some value, then push "Set empty value", you will see model become empty but not input.

https://jsfiddle.net/196e7sr9/

Also i think "min-len" option doesn't work, in example trigger fires when i write only one symbol.

**Comment by dflourusso** [comment]
@saxap 

1. To set an empty value to model, i'll investigate more about it.
2. "min-len" is working normally. You are setting all items when component is loaded. You need to do it only after "update-items" trigger like: 

```javascript
Vue.use(VAutocomplete.default);

Vue.component('test-component', {
  data: function() {
    return {
      items: ['option1', 'option2', 'option3', 'option4', 'option5'],
      itemsFiltered: [],
      selected_value: '',
    }
  },
  template: '<div>Selected value: {{selected_value}}\
  <v-autocomplete :items="itemsFiltered" :auto-select-one-item="false" v-model="selected_value" @update-items="update" :min-len="3"></v-autocomplete>\
  <button @click="setEmptyValue()">Set empty value</button><button @click="setNoEmptyValue()">Set NO empty value</button></div>',
  methods: {
    update: function(text) {
      this.itemsFiltered = this.items.filter(function(p) {
      	return new RegExp(text).test(p)
      })
    },
    setEmptyValue() {
    	this.selected_value = '';
    },
    setNoEmptyValue() {
    	this.selected_value = '333333';
    }
  }
});



var test_app = new Vue({
	el: "#test_app",
	data: {}
});
```

**Comment by saxap** [comment]
Thanks! =)

**Comment by paliari** [comment]
fixed in version 1.8.1

**Comment by saxap** [comment]
Model сlearing is work now, but appears 2 bad things:
1) After selecting item when i try to change input string input is fully clearing
2) On selected event if i try to reset model value this does not happen

https://jsfiddle.net/196e7sr9/2/

**Comment by paliari** [comment]
You can use the **get-label** property to return the custom value.
[See **get-label** property in #properties](https://github.com/paliari/v-autocomplete#properties)

**Comment by saxap** [comment]
It helps me to set empty value in input but model ignore it.
And what about my first list item? After selecting item, try to modify value in input, then value becomes empty =(
I modifyed my example: https://jsfiddle.net/196e7sr9/3/

**Comment by abattenb** [comment]
I got the same issue. One, not-so-great way to get around this is by setting an instant timeout.

> setTimeout(() => this.setEmptyValue(), 0);
