### ISSUE TITLE
Event on input focus

### ISSUE THREAD

**Issue by aBernaciak** [paliari/v-autocomplete#35]
Hello, thanks for great plugin.

Got question, beacuse i can't find it in documentation:
Is there a way to trigger event when input is focused? 

Thanks

**Comment by paliari** [comment]
Tanks
will be implemented in the next version.

**Comment by aBernaciak** [comment]
Thanks a lot, cheers :)

**Comment by paliari** [comment]
implemented in version 1.8.2
