### ISSUE TITLE
Min-len Number required error

### ISSUE THREAD

**Issue by joshua1** [paliari/v-autocomplete#4]
Can the value for Minlength be parsed to an integer before throwing the error 
```
vue.esm.js?65d7:558 [Vue warn]: Invalid prop: type check failed for prop "minLen". Expected Number, got String. 
```
As there is no way you can specify attribute value without the "" in html. Setting the Min length value gives the above error whether directly or via a component property

**Comment by paliari** [comment]
This is happening because of the vue.js syntax. Without ":" the value is a string, with ":" the value is a number.
Use ":" before the property

```html
<v-autocomplete :items="items" :min-len="5">
</v-autocomplete>
```

see [v-bind](https://vuejs.org/v2/api/#v-bind)

**Comment by joshua1** [comment]
Thanks @paliari
