### ISSUE TITLE
FeatureRequest: Clear on select

### ISSUE THREAD

**Issue by telamon** [paliari/v-autocomplete#43]
Would it be possible to clear the input when selecting an item? 
Cannot find any option for this behaviour so I assume it's not implemented.
Would it be possible to modify the value of the v-autocomplete component outside of the component?

**Comment by paliari** [comment]
The input is overwritten with the value returned in the get-label method when selecting the item.

**Comment by telamon** [comment]
So if the get-label method returns null or empty string then that should equal a cleared result? 
Thank you! :)

**Comment by paliari** [comment]
This you customize with the methods updateItems and getLabel, you have complete freedom to overwrite and customize according to your need.
