### ISSUE TITLE
TypeError: Cannot read property 'displayName' of null"

### ISSUE THREAD

**Issue by jamesgill3** [paliari/v-autocomplete#45]
When an item is selected, but clear the text in your input field, there is a  warning on the value watcher:

`[Vue warn]: Error in callback for watcher "value": "TypeError: Cannot read property 'displayName' of null"`

**Comment by paliari** [comment]
this must be occurring in the get-label method, check its logic in it.

**Comment by jamesgill3** [comment]
Apologies, yes it was, thank you
