### ISSUE TITLE
consider using `input[type=text]` or allow to override

### ISSUE THREAD

**Issue by arve0** [paliari/v-autocomplete#57]
Hi! Thanks for the package 👍 
Styling the input [requires](https://css-tricks.com/webkit-html5-search-inputs/) `-webkit-appearance: textfield`, or `none`. I see that you use it in the demo CSS, but this is not documented.

Also, `type=search` has a special meaning; for example, I get suggestions from my contacts on OS X. This is not what I want, and I assume most people do not want this either. Rather, suggestions should only be from the `items` attribute.

Changing input type to text will solve all above.

**Comment by tbtalbottjr** [comment]
I am running into this problem as well. Need to override 'type'. Autocomplete is not limited to search fields.

**Comment by chris-oswald** [comment]
I want to echo this request and ability to override
