### ISSUE TITLE
Item Selected doesn't always run when the page is created

### ISSUE THREAD

**Issue by smaharj1** [paliari/v-autocomplete#64]
I am trying to figure out what is wrong with the populating initial value. Whenever I navigate to the page with autocomplete, v-model/value should give the initial value for the input field. However, I am not seeing this behavior. I have put `v-model="local_id"` where local_id is the initial text that is given to the component. I cannot see the initial value every time even though local_id has an initial value. Whenever I switch between pages and come back to Autocomplete page, it only gets the label sometimes. 

When I checked, it looks like my get-label and item-selected don't run every time I go to the page.

**Comment by z3malford** [comment]
I'm having a similar problem.

~~~
	<v-autocomplete
		:items="myOptions"
		:get-label="getMyLabel"
		:minLen="1"
		:componentItem="AutocompleteItem"
		v-model="myValue"
		@update-items="updateItems"
		@change="changeEvent"
	>
	</v-autocomplete>
~~~

When `myValue` is changed, the `input` element isn't getting updated.

The use model for this is, I'm ajax loading `items` and if there is only a single item, I want to have it in the input and selected like what the `auto-select-one-item` is supposed to do. However, this behavior doesn't happen the first time I ajax load the v-autocomplete. However, it does happen when I do a subsequent `update-items` triggered ajax relaod of `items`.

**Comment by z3malford** [comment]
I found a solution that works for me. There seems to be a problem with the `value` watcher:

~~~javascript
		value (newValue) {
//			if (!this.isSelectedValue(newValue) ) { // BEFORE
			if (this.isSelectedValue(newValue) ) { // AFTER
				this.onSelectItem(newValue)
				this.searchText = this.getLabel(newValue)
			}
		}
~~~

The `if` logic seems to be inverted? Does that make sense?

**Comment by smaharj1** [comment]
I figured out the solution. My ajax call was being handled in a separate thread and I was setting my value asynchronously. It created the race condition which is why the text didn't always appear.
