### ISSUE TITLE
Option to add CSS class to input element

### ISSUE THREAD

**Issue by matthewpull** [paliari/v-autocomplete#7]
I'm using the Bulma CSS library and would like to be able to add a .input class to the inner input element of the autocomplete. Ideally, it would be great if v-autocomplete exposed a property that allowed a class to be added to the inner input element.

Thanks :)

**Comment by paliari** [comment]
published last version
https://github.com/paliari/v-autocomplete/blob/master/README.md#properties

**Comment by matthewpull** [comment]
Awesome, thanks!
