### ISSUE TITLE
Expand items on first click

### ISSUE THREAD

**Issue by jfeid** [paliari/v-autocomplete#73]
Hi,

Many thanks for this nice component.

I am using it with `"min-len" = "0"` because I want to expand the items right after clicking on it. This feature seems to work **only** after typing something, then emptying the search box and clicking again. It does not expand the items on the first click.

Any idea on how to expand items on first click?

**Comment by jkatagi** [comment]
@jfeid 
Hi, I achieved it by adding `@focus=update` to `v-autocomplete` and set a default item as empty.

This is based on the fact that `focus` is called when clicking on the input field (it returns the search result with empty string.).

It looks like that (changed [this demo code](https://github.com/paliari/v-autocomplete/blob/master/demo/App.vue))

```javascript
...
# inside template
 v-autocomplete(@focus='update', :items="items" v-model='item', :get-label='getLabel', :min-len='0' @update-items='update', :component-item='tpl', @item-selected="itemSelected", @item-clicked="itemClicked", :input-attrs="{name: 'input-test', id: 'v-my-autocomplete'}")
...
# inside script
      item: {id: '', name: '', description: ''},
```

**Comment by jfeid** [comment]
Thanks!
